import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | xHeal",
};

export default function PrivacyPolicyPage() {
  return (
    <>
      {/* Hero */}
      <section
        className="relative"
        style={{
          backgroundImage:
            "linear-gradient(180deg, var(--dark-blue), #f8f8fa00)",
        }}
      >
        <div className="w-full max-w-[100em] mx-auto px-[5em] pt-[200px] pb-[5em] flex flex-col items-center gap-[40px] text-xwhite max-[991px]:px-[40px] max-[991px]:pt-[140px] max-[479px]:px-[20px]">
          <h1 className="text-[4.5rem] font-medium leading-[1] tracking-[-0.04em] text-center max-[991px]:text-[3.5rem] max-[479px]:text-[3rem]">
            Privacy Policy
          </h1>
        </div>
      </section>

      {/* Content */}
      <section>
        <div className="w-full max-w-[100em] mx-auto px-[5em] py-[5em] flex flex-col items-center gap-[40px] text-xblack max-[991px]:px-[40px] max-[479px]:px-[20px]">
          <div className="rich-text w-full max-w-[800px]">
            <p>
              <strong>Last Updated: December 15, 2025</strong>
            </p>

            <h2>1. Introduction</h2>
            <p>
              xHeal Corp. (&quot;xHeal,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) is committed to
              protecting the privacy and security of your personal data. This
              Privacy Policy (&quot;Policy&quot;) explains how we collect, use, share,
              and protect information when you use the xHeal mobile application
              (the &quot;App&quot;), our website at{" "}
              <a href="https://xheal.ai">https://xheal.ai</a> (the &quot;Website&quot;),
              and all related services, features, content, and functionality
              (collectively, the &quot;Services&quot;).
            </p>
            <p>
              xHeal Corp. is incorporated in the State of Florida, United
              States, with its principal office at 25 SE 2ND AVE, SUITE 550,
              MIAMI, FL 33131, USA. For the purposes of applicable data
              protection laws, xHeal Corp. is the data controller responsible
              for your personal data.
            </p>
            <p>
              By using our Services, you acknowledge that you have read and
              understood this Policy. If you do not agree with this Policy,
              please do not use our Services.
            </p>

            <h2>2. How We Collect Personal Data</h2>
            <p>
              We collect personal data in the following ways:
            </p>
            <ul>
              <li>
                <strong>Directly from you:</strong> When you create an account,
                fill in your health profile, input health data, use the xHeal
                Chat, upload medical documents, subscribe to our Services, or
                contact our support team.
              </li>
              <li>
                <strong>Automatically:</strong> When you use our Services, we
                automatically collect certain technical and usage data through
                cookies, log files, analytics tools, and similar technologies.
              </li>
              <li>
                <strong>From third-party sources:</strong> We may receive data
                from connected health devices and wearables (e.g., Apple
                Health, Google Health Connect), third-party sign-in providers
                (e.g., Apple Sign-In, Google Sign-In), payment processors, and
                analytics providers.
              </li>
            </ul>

            <h2>3. What Personal Data We Collect</h2>
            <p>
              We may collect the following categories of personal data:
            </p>
            <ul>
              <li>
                <strong>Account Information:</strong> Name, email address,
                password (encrypted), date of birth, gender, profile photo, and
                account preferences.
              </li>
              <li>
                <strong>Health and Wellness Data:</strong> Vitals (e.g., heart
                rate, blood pressure, weight, body temperature), medical
                records and documents you upload, symptoms and flare-up logs,
                dietary information, exercise and activity data, sleep data,
                mental wellness inputs, and health scores generated by our
                Services.
              </li>
              <li>
                <strong>Device and Wearable Data:</strong> Data synced from
                connected health devices, Apple Health, Google Health Connect,
                and other third-party health platforms you authorize.
              </li>
              <li>
                <strong>Usage Data:</strong> Information about how you interact
                with our Services, including features used, pages visited, time
                spent, clicks, and navigation patterns.
              </li>
              <li>
                <strong>Device Information:</strong> Device type, operating
                system and version, unique device identifiers, IP address,
                browser type, and language preferences.
              </li>
              <li>
                <strong>Payment Information:</strong> Payment method details are
                processed by third-party payment processors (e.g., Apple,
                Google, Stripe). We do not store your full credit card number or
                payment credentials on our servers.
              </li>
              <li>
                <strong>Communications Data:</strong> Messages sent through
                xHeal Chat, support inquiries, feedback, and any other
                communications you have with us.
              </li>
              <li>
                <strong>Location Data:</strong> General location information
                derived from your IP address. We do not collect precise GPS
                location data.
              </li>
            </ul>

            <h2>4. Cookies and Similar Technologies</h2>
            <p>
              We use cookies, pixels, and similar tracking technologies on our
              Website and in our Services to enhance your experience, analyze
              usage, and deliver relevant content. For detailed information
              about the cookies we use and how to manage your preferences,
              please see our <a href="/cookie-policy">Cookie Policy</a>.
            </p>

            <h2>5. How We Use Collected Personal Data</h2>
            <p>
              We use your personal data for the following purposes:
            </p>
            <ul>
              <li>
                <strong>Providing and Improving Services:</strong> To operate,
                maintain, and improve the Services, including generating health
                insights, scores, reports, and personalized recommendations.
              </li>
              <li>
                <strong>AI-Powered Features:</strong> To train, develop, and
                improve our AI and machine learning models that power health
                insights and the xHeal Chat. Where we use your data for AI
                training, it is anonymized and aggregated so that it cannot
                identify you personally.
              </li>
              <li>
                <strong>Account Management:</strong> To create and manage your
                account, process subscriptions and payments, and provide
                customer support.
              </li>
              <li>
                <strong>Communications:</strong> To send you transactional
                messages (e.g., account confirmations, billing notifications,
                security alerts), as well as marketing and promotional
                communications where you have opted in.
              </li>
              <li>
                <strong>Analytics and Research:</strong> To understand usage
                trends, monitor the effectiveness of our Services, conduct
                research and analysis, and develop new features.
              </li>
              <li>
                <strong>Security and Fraud Prevention:</strong> To detect,
                prevent, and address security incidents, fraud, and other
                harmful activities.
              </li>
              <li>
                <strong>Legal Compliance:</strong> To comply with applicable
                laws, regulations, legal processes, and governmental requests.
              </li>
            </ul>

            <h2>6. How We Share Personal Data</h2>
            <p>
              We do not sell your personal data. We may share your personal data
              in the following circumstances:
            </p>
            <ul>
              <li>
                <strong>Service Providers:</strong> We share data with
                trusted third-party service providers who perform functions on
                our behalf, such as cloud hosting (AWS), analytics, payment
                processing, email delivery, and customer support. These
                providers are contractually required to protect your data and
                may only use it for the purposes specified by us.
              </li>
              <li>
                <strong>AI Technology Providers:</strong> We may share
                anonymized and de-identified data with third-party AI
                technology providers to power certain features of the Services,
                such as the xHeal Chat. We do not share personally identifiable
                health information with these providers without your explicit
                consent.
              </li>
              <li>
                <strong>Legal Requirements:</strong> We may disclose your data
                when required by law, regulation, legal process, or
                governmental request, or when we believe disclosure is necessary
                to protect the rights, property, or safety of xHeal, our users,
                or others.
              </li>
              <li>
                <strong>Business Transfers:</strong> In the event of a merger,
                acquisition, reorganization, or sale of all or a portion of our
                assets, your personal data may be transferred to the acquiring
                entity.
              </li>
              <li>
                <strong>With Your Consent:</strong> We may share your data for
                other purposes with your explicit consent.
              </li>
            </ul>

            <h2>7. How You May Share Personal Data</h2>
            <p>
              The Services may allow you to share your health data, reports, or
              other information with third parties, such as healthcare
              providers, family members, or other individuals you designate.
              When you choose to share your data with third parties, their use
              of your data is governed by their own privacy practices and
              policies. xHeal is not responsible for the privacy practices of
              third parties with whom you share your data.
            </p>

            <h2>8. xHeal Chat &amp; Third-Party AI Technology</h2>
            <p>
              The xHeal Chat feature is powered by artificial intelligence
              technology, which may include third-party AI models. When you
              interact with xHeal Chat:
            </p>
            <ul>
              <li>
                Your messages and inputs are processed to generate responses and
                health insights.
              </li>
              <li>
                We may transmit anonymized or de-identified portions of your
                inputs to third-party AI providers to facilitate responses.
              </li>
              <li>
                We implement technical and organizational measures to minimize
                the personal data shared with third-party AI providers.
              </li>
              <li>
                Chat conversations may be stored to improve the quality and
                accuracy of future interactions and to enhance our AI models.
              </li>
              <li>
                You should not share highly sensitive personal information
                (e.g., Social Security numbers, financial account numbers) in
                Chat conversations.
              </li>
            </ul>

            <h2>9. Your Choices</h2>
            <p>
              You have the following choices regarding your personal data:
            </p>
            <ul>
              <li>
                <strong>Account Information:</strong> You can review and update
                your account information through the App settings at any time.
              </li>
              <li>
                <strong>Marketing Communications:</strong> You can opt out of
                marketing emails by clicking the &quot;unsubscribe&quot; link in any
                marketing email or by updating your communication preferences
                in the App settings.
              </li>
              <li>
                <strong>Cookies:</strong> You can manage your cookie
                preferences through your browser settings or through the cookie
                consent mechanism on our Website. See our{" "}
                <a href="/cookie-policy">Cookie Policy</a> for more details.
              </li>
              <li>
                <strong>Data Portability:</strong> You may request a copy of
                your personal data in a structured, commonly used, and
                machine-readable format by contacting us at{" "}
                <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a>.
              </li>
              <li>
                <strong>Account Deletion:</strong> You may request deletion of
                your account and associated personal data by contacting us at{" "}
                <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a> or
                through the account settings in the App. Please note that some
                data may be retained as required by law or for legitimate
                business purposes.
              </li>
              <li>
                <strong>Connected Devices:</strong> You can disconnect health
                devices and wearables from the App at any time through the App
                settings.
              </li>
            </ul>

            <h2>10. Data Security and Retention</h2>
            <p>
              We implement industry-standard technical and organizational
              security measures to protect your personal data against
              unauthorized access, alteration, disclosure, or destruction. These
              measures include encryption in transit (TLS) and at rest (AES-256),
              access controls, regular security assessments, and secure cloud
              infrastructure (AWS).
            </p>
            <p>
              However, no method of transmission over the Internet or method of
              electronic storage is 100% secure. While we strive to use
              commercially acceptable means to protect your personal data, we
              cannot guarantee its absolute security.
            </p>
            <p>
              We retain your personal data for as long as your account is
              active or as needed to provide you with the Services. When your
              account is deleted, we will delete or anonymize your personal data
              within 90 days, except where retention is required by law, for
              dispute resolution, or for legitimate business purposes. Anonymized
              and aggregated data that cannot identify you may be retained
              indefinitely for research and analytics purposes.
            </p>

            <h2>11. Services Not Intended for Children</h2>
            <p>
              Our Services are not directed to children under the age of 13 (or
              16 in the European Union). We do not knowingly collect personal
              data from children under these ages. If we become aware that we
              have collected personal data from a child under the applicable
              age threshold, we will take steps to delete such data promptly.
              If you believe that a child has provided us with personal data,
              please contact us at{" "}
              <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a>.
            </p>

            <h2>12. Changes to This Privacy Policy</h2>
            <p>
              We may update this Policy from time to time. If we make material
              changes, we will notify you by posting the updated Policy on the
              Website and within the App, and where required by law, by sending
              you an email or in-app notification. The &quot;Last Updated&quot; date at
              the top of this Policy indicates when it was last revised. Your
              continued use of the Services after the effective date of the
              revised Policy constitutes your acceptance of the changes.
            </p>

            <h2>13. Contact Us</h2>
            <p>
              If you have questions, concerns, or requests regarding this
              Privacy Policy or our data practices, please contact us:
            </p>
            <p>
              <strong>xHeal Corp.</strong>
              <br />
              25 SE 2ND AVE, SUITE 550
              <br />
              MIAMI, FL 33131, USA
            </p>
            <ul>
              <li>
                General Privacy Inquiries:{" "}
                <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a>
              </li>
              <li>
                Data Protection Officer:{" "}
                <a href="mailto:dpo@xheal.ai">dpo@xheal.ai</a>
              </li>
              <li>
                EU Representative:{" "}
                <a href="mailto:eu-representative@xheal.ai">
                  eu-representative@xheal.ai
                </a>
              </li>
              <li>
                Support:{" "}
                <a href="mailto:support@xheal.ai">support@xheal.ai</a>
              </li>
              <li>
                Legal:{" "}
                <a href="mailto:legal@xheal.ai">legal@xheal.ai</a>
              </li>
              <li>Phone: (833) 514-4187</li>
            </ul>

            <h2>14. U.S. State-Specific Privacy Notice</h2>
            <p>
              This section provides additional information for residents of U.S.
              states with comprehensive privacy legislation, including
              California (CCPA/CPRA), Virginia (VCDPA), Colorado (CPA),
              Connecticut (CTDPA), and other states with similar laws.
            </p>

            <h3>Categories of Personal Information Collected</h3>
            <p>
              In the preceding 12 months, we have collected the following
              categories of personal information as defined under applicable
              state privacy laws:
            </p>
            <ul>
              <li>
                Identifiers (e.g., name, email address, account ID, IP
                address).
              </li>
              <li>
                Personal information categories listed in the relevant state
                statutes (e.g., name, address, telephone number).
              </li>
              <li>
                Protected classification characteristics (e.g., age, gender).
              </li>
              <li>
                Commercial information (e.g., subscription history, payment
                records).
              </li>
              <li>
                Internet or other electronic network activity information (e.g.,
                browsing history, interaction data, device information).
              </li>
              <li>
                Sensory data (e.g., health data, biometric data from connected
                devices).
              </li>
              <li>
                Inferences drawn from the above (e.g., health scores and AI
                insights).
              </li>
            </ul>

            <h3>Your State Privacy Rights</h3>
            <p>
              Depending on your state of residence, you may have the following
              rights:
            </p>
            <ul>
              <li>
                <strong>Right to Know:</strong> Request information about the
                categories and specific pieces of personal information we have
                collected about you.
              </li>
              <li>
                <strong>Right to Delete:</strong> Request deletion of personal
                information we have collected from you, subject to certain
                exceptions.
              </li>
              <li>
                <strong>Right to Correct:</strong> Request correction of
                inaccurate personal information.
              </li>
              <li>
                <strong>Right to Opt Out:</strong> Opt out of the sale or
                sharing of personal information. xHeal does not sell your
                personal information.
              </li>
              <li>
                <strong>Right to Non-Discrimination:</strong> Exercise your
                privacy rights without receiving discriminatory treatment.
              </li>
            </ul>
            <p>
              To exercise any of these rights, contact us at{" "}
              <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a>. We will
              verify your identity before processing your request.
            </p>

            <h2>15. Trans-Atlantic Data Privacy Framework</h2>
            <p>
              xHeal may transfer personal data from the European Economic Area
              (EEA), United Kingdom (UK), and Switzerland to the United States.
              When we do so, we rely on the following transfer mechanisms to
              ensure adequate protection of your data:
            </p>
            <ul>
              <li>
                <strong>Standard Contractual Clauses (SCCs):</strong> We enter
                into EU-approved Standard Contractual Clauses with our service
                providers and partners who process data outside the EEA.
              </li>
              <li>
                <strong>Adequacy Decisions:</strong> Where applicable, we
                transfer data to countries that the European Commission has
                determined provide an adequate level of data protection.
              </li>
              <li>
                <strong>Supplementary Measures:</strong> We implement additional
                technical and organizational measures (e.g., encryption, access
                controls) to supplement the safeguards provided by SCCs where
                necessary.
              </li>
            </ul>
            <p>
              For further information about our cross-border data transfer
              practices, please contact our Data Protection Officer at{" "}
              <a href="mailto:dpo@xheal.ai">dpo@xheal.ai</a>.
            </p>

            <h2>16. Privacy Notice for European Residents (GDPR)</h2>
            <p>
              This section provides additional information for individuals
              located in the European Economic Area (EEA), United Kingdom (UK),
              and Switzerland, as required by the General Data Protection
              Regulation (GDPR) and equivalent legislation.
            </p>

            <h3>Legal Bases for Processing</h3>
            <p>
              We process your personal data on the following legal bases:
            </p>
            <ul>
              <li>
                <strong>Contract Performance:</strong> Processing necessary to
                perform our contract with you (e.g., providing the Services,
                managing your account, processing payments).
              </li>
              <li>
                <strong>Consent:</strong> Processing based on your freely given,
                specific, informed, and unambiguous consent (e.g., processing
                special categories of health data, sending marketing
                communications).
              </li>
              <li>
                <strong>Legitimate Interests:</strong> Processing necessary for
                our legitimate interests, provided these interests are not
                overridden by your fundamental rights and freedoms (e.g.,
                improving our Services, fraud prevention, security).
              </li>
              <li>
                <strong>Legal Obligation:</strong> Processing necessary to
                comply with legal obligations to which we are subject.
              </li>
            </ul>

            <h3>Your Rights Under GDPR</h3>
            <p>
              As a data subject in the EEA, UK, or Switzerland, you have the
              following rights:
            </p>
            <ul>
              <li>
                <strong>Right of Access:</strong> Request a copy of the personal
                data we hold about you.
              </li>
              <li>
                <strong>Right to Rectification:</strong> Request correction of
                inaccurate or incomplete personal data.
              </li>
              <li>
                <strong>Right to Erasure:</strong> Request deletion of your
                personal data in certain circumstances.
              </li>
              <li>
                <strong>Right to Restriction:</strong> Request restriction of
                processing of your personal data in certain circumstances.
              </li>
              <li>
                <strong>Right to Data Portability:</strong> Receive your
                personal data in a structured, commonly used, and
                machine-readable format.
              </li>
              <li>
                <strong>Right to Object:</strong> Object to processing of your
                personal data based on legitimate interests or for direct
                marketing purposes.
              </li>
              <li>
                <strong>Right to Withdraw Consent:</strong> Where processing is
                based on consent, you have the right to withdraw your consent at
                any time without affecting the lawfulness of processing based on
                consent before its withdrawal.
              </li>
              <li>
                <strong>Right to Lodge a Complaint:</strong> You have the right
                to lodge a complaint with your local data protection authority
                (supervisory authority).
              </li>
            </ul>
            <p>
              To exercise any of these rights, please contact our Data
              Protection Officer at{" "}
              <a href="mailto:dpo@xheal.ai">dpo@xheal.ai</a> or our EU
              Representative at{" "}
              <a href="mailto:eu-representative@xheal.ai">
                eu-representative@xheal.ai
              </a>
              .
            </p>

            <h3>Special Categories of Data</h3>
            <p>
              Certain health and wellness data we process may constitute
              &quot;special categories of personal data&quot; under the GDPR. We process
              such data only with your explicit consent, which you provide when
              creating your account and inputting health data into the Services.
              You may withdraw your consent at any time by contacting us or
              deleting your account.
            </p>

            <h3>Data Retention for European Residents</h3>
            <p>
              We retain your personal data only for as long as necessary to
              fulfill the purposes for which it was collected, including
              satisfying any legal, accounting, or reporting requirements. Upon
              account deletion, your personal data will be erased within 30 days,
              unless a longer retention period is required or permitted by law.
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
