// Legal page content for EN and BG locales
// Content stored as HTML strings for use with dangerouslySetInnerHTML

export interface LegalContent {
  title: string;
  metaTitle: string;
  content: string;
}

export interface LegalPages {
  privacyPolicy: LegalContent;
  termsConditions: LegalContent;
  cookiePolicy: LegalContent;
}

// ============================================================
// ENGLISH
// ============================================================

const legalEn: LegalPages = {
  privacyPolicy: {
    title: "Privacy Policy",
    metaTitle: "Privacy Policy | xHeal",
    content: `<p><strong>Last Updated: December 15, 2025</strong></p>

<h2>1. Introduction</h2>
<p>xHeal Corp. ("xHeal," "we," "us," or "our") is committed to protecting the privacy and security of your personal data. This Privacy Policy ("Policy") explains how we collect, use, share, and protect information when you use the xHeal mobile application (the "App"), our website at <a href="https://xheal.ai">https://xheal.ai</a> (the "Website"), and all related services, features, content, and functionality (collectively, the "Services").</p>
<p>xHeal Corp. is incorporated in the State of Florida, United States, with its principal office at 25 SE 2ND AVE, SUITE 550, MIAMI, FL 33131, USA. For the purposes of applicable data protection laws, xHeal Corp. is the data controller responsible for your personal data.</p>
<p>By using our Services, you acknowledge that you have read and understood this Policy. If you do not agree with this Policy, please do not use our Services.</p>

<h2>2. How We Collect Personal Data</h2>
<p>We collect personal data in the following ways:</p>
<ul>
<li><strong>Directly from you:</strong> When you create an account, fill in your health profile, input health data, use the xHeal Chat, upload medical documents, subscribe to our Services, or contact our support team.</li>
<li><strong>Automatically:</strong> When you use our Services, we automatically collect certain technical and usage data through cookies, log files, analytics tools, and similar technologies.</li>
<li><strong>From third-party sources:</strong> We may receive data from connected health devices and wearables (e.g., Apple Health, Google Health Connect), third-party sign-in providers (e.g., Apple Sign-In, Google Sign-In), payment processors, and analytics providers.</li>
</ul>

<h2>3. What Personal Data We Collect</h2>
<p>We may collect the following categories of personal data:</p>
<ul>
<li><strong>Account Information:</strong> Name, email address, password (encrypted), date of birth, gender, profile photo, and account preferences.</li>
<li><strong>Health and Wellness Data:</strong> Vitals (e.g., heart rate, blood pressure, weight, body temperature), medical records and documents you upload, symptoms and flare-up logs, dietary information, exercise and activity data, sleep data, mental wellness inputs, and health scores generated by our Services.</li>
<li><strong>Device and Wearable Data:</strong> Data synced from connected health devices, Apple Health, Google Health Connect, and other third-party health platforms you authorize.</li>
<li><strong>Usage Data:</strong> Information about how you interact with our Services, including features used, pages visited, time spent, clicks, and navigation patterns.</li>
<li><strong>Device Information:</strong> Device type, operating system and version, unique device identifiers, IP address, browser type, and language preferences.</li>
<li><strong>Payment Information:</strong> Payment method details are processed by third-party payment processors (e.g., Apple, Google, Stripe). We do not store your full credit card number or payment credentials on our servers.</li>
<li><strong>Communications Data:</strong> Messages sent through xHeal Chat, support inquiries, feedback, and any other communications you have with us.</li>
<li><strong>Location Data:</strong> General location information derived from your IP address. We do not collect precise GPS location data.</li>
</ul>

<h2>4. Cookies and Similar Technologies</h2>
<p>We use cookies, pixels, and similar tracking technologies on our Website and in our Services to enhance your experience, analyze usage, and deliver relevant content. For detailed information about the cookies we use and how to manage your preferences, please see our <a href="/cookie-policy">Cookie Policy</a>.</p>

<h2>5. How We Use Collected Personal Data</h2>
<p>We use your personal data for the following purposes:</p>
<ul>
<li><strong>Providing and Improving Services:</strong> To operate, maintain, and improve the Services, including generating health insights, scores, reports, and personalized recommendations.</li>
<li><strong>AI-Powered Features:</strong> To train, develop, and improve our AI and machine learning models that power health insights and the xHeal Chat. Where we use your data for AI training, it is anonymized and aggregated so that it cannot identify you personally.</li>
<li><strong>Account Management:</strong> To create and manage your account, process subscriptions and payments, and provide customer support.</li>
<li><strong>Communications:</strong> To send you transactional messages (e.g., account confirmations, billing notifications, security alerts), as well as marketing and promotional communications where you have opted in.</li>
<li><strong>Analytics and Research:</strong> To understand usage trends, monitor the effectiveness of our Services, conduct research and analysis, and develop new features.</li>
<li><strong>Security and Fraud Prevention:</strong> To detect, prevent, and address security incidents, fraud, and other harmful activities.</li>
<li><strong>Legal Compliance:</strong> To comply with applicable laws, regulations, legal processes, and governmental requests.</li>
</ul>

<h2>6. How We Share Personal Data</h2>
<p>We do not sell your personal data. We may share your personal data in the following circumstances:</p>
<ul>
<li><strong>Service Providers:</strong> We share data with trusted third-party service providers who perform functions on our behalf, such as cloud hosting (AWS), analytics, payment processing, email delivery, and customer support. These providers are contractually required to protect your data and may only use it for the purposes specified by us.</li>
<li><strong>AI Technology Providers:</strong> We may share anonymized and de-identified data with third-party AI technology providers to power certain features of the Services, such as the xHeal Chat. We do not share personally identifiable health information with these providers without your explicit consent.</li>
<li><strong>Legal Requirements:</strong> We may disclose your data when required by law, regulation, legal process, or governmental request, or when we believe disclosure is necessary to protect the rights, property, or safety of xHeal, our users, or others.</li>
<li><strong>Business Transfers:</strong> In the event of a merger, acquisition, reorganization, or sale of all or a portion of our assets, your personal data may be transferred to the acquiring entity.</li>
<li><strong>With Your Consent:</strong> We may share your data for other purposes with your explicit consent.</li>
</ul>

<h2>7. How You May Share Personal Data</h2>
<p>The Services may allow you to share your health data, reports, or other information with third parties, such as healthcare providers, family members, or other individuals you designate. When you choose to share your data with third parties, their use of your data is governed by their own privacy practices and policies. xHeal is not responsible for the privacy practices of third parties with whom you share your data.</p>

<h2>8. xHeal Chat &amp; Third-Party AI Technology</h2>
<p>The xHeal Chat feature is powered by artificial intelligence technology, which may include third-party AI models. When you interact with xHeal Chat:</p>
<ul>
<li>Your messages and inputs are processed to generate responses and health insights.</li>
<li>We may transmit anonymized or de-identified portions of your inputs to third-party AI providers to facilitate responses.</li>
<li>We implement technical and organizational measures to minimize the personal data shared with third-party AI providers.</li>
<li>Chat conversations may be stored to improve the quality and accuracy of future interactions and to enhance our AI models.</li>
<li>You should not share highly sensitive personal information (e.g., Social Security numbers, financial account numbers) in Chat conversations.</li>
</ul>

<h2>9. Your Choices</h2>
<p>You have the following choices regarding your personal data:</p>
<ul>
<li><strong>Account Information:</strong> You can review and update your account information through the App settings at any time.</li>
<li><strong>Marketing Communications:</strong> You can opt out of marketing emails by clicking the "unsubscribe" link in any marketing email or by updating your communication preferences in the App settings.</li>
<li><strong>Cookies:</strong> You can manage your cookie preferences through your browser settings or through the cookie consent mechanism on our Website. See our <a href="/cookie-policy">Cookie Policy</a> for more details.</li>
<li><strong>Data Portability:</strong> You may request a copy of your personal data in a structured, commonly used, and machine-readable format by contacting us at <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a>.</li>
<li><strong>Account Deletion:</strong> You may request deletion of your account and associated personal data by contacting us at <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a> or through the account settings in the App. Please note that some data may be retained as required by law or for legitimate business purposes.</li>
<li><strong>Connected Devices:</strong> You can disconnect health devices and wearables from the App at any time through the App settings.</li>
</ul>

<h2>10. Data Security and Retention</h2>
<p>We implement industry-standard technical and organizational security measures to protect your personal data against unauthorized access, alteration, disclosure, or destruction. These measures include encryption in transit (TLS) and at rest (AES-256), access controls, regular security assessments, and secure cloud infrastructure (AWS).</p>
<p>However, no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal data, we cannot guarantee its absolute security.</p>
<p>We retain your personal data for as long as your account is active or as needed to provide you with the Services. When your account is deleted, we will delete or anonymize your personal data within 90 days, except where retention is required by law, for dispute resolution, or for legitimate business purposes. Anonymized and aggregated data that cannot identify you may be retained indefinitely for research and analytics purposes.</p>

<h2>11. Services Not Intended for Children</h2>
<p>Our Services are not directed to children under the age of 13 (or 16 in the European Union). We do not knowingly collect personal data from children under these ages. If we become aware that we have collected personal data from a child under the applicable age threshold, we will take steps to delete such data promptly. If you believe that a child has provided us with personal data, please contact us at <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a>.</p>

<h2>12. Changes to This Privacy Policy</h2>
<p>We may update this Policy from time to time. If we make material changes, we will notify you by posting the updated Policy on the Website and within the App, and where required by law, by sending you an email or in-app notification. The "Last Updated" date at the top of this Policy indicates when it was last revised. Your continued use of the Services after the effective date of the revised Policy constitutes your acceptance of the changes.</p>

<h2>13. Contact Us</h2>
<p>If you have questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:</p>
<p><strong>xHeal Corp.</strong><br>25 SE 2ND AVE, SUITE 550<br>MIAMI, FL 33131, USA</p>
<ul>
<li>General Privacy Inquiries: <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a></li>
<li>Data Protection Officer: <a href="mailto:dpo@xheal.ai">dpo@xheal.ai</a></li>
<li>EU Representative: <a href="mailto:eu-representative@xheal.ai">eu-representative@xheal.ai</a></li>
<li>Support: <a href="mailto:support@xheal.ai">support@xheal.ai</a></li>
<li>Legal: <a href="mailto:legal@xheal.ai">legal@xheal.ai</a></li>
<li>Phone: (833) 514-4187</li>
</ul>

<h2>14. U.S. State-Specific Privacy Notice</h2>
<p>This section provides additional information for residents of U.S. states with comprehensive privacy legislation, including California (CCPA/CPRA), Virginia (VCDPA), Colorado (CPA), Connecticut (CTDPA), and other states with similar laws.</p>
<h3>Categories of Personal Information Collected</h3>
<p>In the preceding 12 months, we have collected the following categories of personal information as defined under applicable state privacy laws:</p>
<ul>
<li>Identifiers (e.g., name, email address, account ID, IP address).</li>
<li>Personal information categories listed in the relevant state statutes (e.g., name, address, telephone number).</li>
<li>Protected classification characteristics (e.g., age, gender).</li>
<li>Commercial information (e.g., subscription history, payment records).</li>
<li>Internet or other electronic network activity information (e.g., browsing history, interaction data, device information).</li>
<li>Sensory data (e.g., health data, biometric data from connected devices).</li>
<li>Inferences drawn from the above (e.g., health scores and AI insights).</li>
</ul>
<h3>Your State Privacy Rights</h3>
<p>Depending on your state of residence, you may have the following rights:</p>
<ul>
<li><strong>Right to Know:</strong> Request information about the categories and specific pieces of personal information we have collected about you.</li>
<li><strong>Right to Delete:</strong> Request deletion of personal information we have collected from you, subject to certain exceptions.</li>
<li><strong>Right to Correct:</strong> Request correction of inaccurate personal information.</li>
<li><strong>Right to Opt Out:</strong> Opt out of the sale or sharing of personal information. xHeal does not sell your personal information.</li>
<li><strong>Right to Non-Discrimination:</strong> Exercise your privacy rights without receiving discriminatory treatment.</li>
</ul>
<p>To exercise any of these rights, contact us at <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a>. We will verify your identity before processing your request.</p>

<h2>15. Trans-Atlantic Data Privacy Framework</h2>
<p>xHeal may transfer personal data from the European Economic Area (EEA), United Kingdom (UK), and Switzerland to the United States. When we do so, we rely on the following transfer mechanisms to ensure adequate protection of your data:</p>
<ul>
<li><strong>Standard Contractual Clauses (SCCs):</strong> We enter into EU-approved Standard Contractual Clauses with our service providers and partners who process data outside the EEA.</li>
<li><strong>Adequacy Decisions:</strong> Where applicable, we transfer data to countries that the European Commission has determined provide an adequate level of data protection.</li>
<li><strong>Supplementary Measures:</strong> We implement additional technical and organizational measures (e.g., encryption, access controls) to supplement the safeguards provided by SCCs where necessary.</li>
</ul>
<p>For further information about our cross-border data transfer practices, please contact our Data Protection Officer at <a href="mailto:dpo@xheal.ai">dpo@xheal.ai</a>.</p>

<h2>16. Privacy Notice for European Residents (GDPR)</h2>
<p>This section provides additional information for individuals located in the European Economic Area (EEA), United Kingdom (UK), and Switzerland, as required by the General Data Protection Regulation (GDPR) and equivalent legislation.</p>
<h3>Legal Bases for Processing</h3>
<p>We process your personal data on the following legal bases:</p>
<ul>
<li><strong>Contract Performance:</strong> Processing necessary to perform our contract with you (e.g., providing the Services, managing your account, processing payments).</li>
<li><strong>Consent:</strong> Processing based on your freely given, specific, informed, and unambiguous consent (e.g., processing special categories of health data, sending marketing communications).</li>
<li><strong>Legitimate Interests:</strong> Processing necessary for our legitimate interests, provided these interests are not overridden by your fundamental rights and freedoms (e.g., improving our Services, fraud prevention, security).</li>
<li><strong>Legal Obligation:</strong> Processing necessary to comply with legal obligations to which we are subject.</li>
</ul>
<h3>Your Rights Under GDPR</h3>
<p>As a data subject in the EEA, UK, or Switzerland, you have the following rights:</p>
<ul>
<li><strong>Right of Access:</strong> Request a copy of the personal data we hold about you.</li>
<li><strong>Right to Rectification:</strong> Request correction of inaccurate or incomplete personal data.</li>
<li><strong>Right to Erasure:</strong> Request deletion of your personal data in certain circumstances.</li>
<li><strong>Right to Restriction:</strong> Request restriction of processing of your personal data in certain circumstances.</li>
<li><strong>Right to Data Portability:</strong> Receive your personal data in a structured, commonly used, and machine-readable format.</li>
<li><strong>Right to Object:</strong> Object to processing of your personal data based on legitimate interests or for direct marketing purposes.</li>
<li><strong>Right to Withdraw Consent:</strong> Where processing is based on consent, you have the right to withdraw your consent at any time without affecting the lawfulness of processing based on consent before its withdrawal.</li>
<li><strong>Right to Lodge a Complaint:</strong> You have the right to lodge a complaint with your local data protection authority (supervisory authority).</li>
</ul>
<p>To exercise any of these rights, please contact our Data Protection Officer at <a href="mailto:dpo@xheal.ai">dpo@xheal.ai</a> or our EU Representative at <a href="mailto:eu-representative@xheal.ai">eu-representative@xheal.ai</a>.</p>
<h3>Special Categories of Data</h3>
<p>Certain health and wellness data we process may constitute "special categories of personal data" under the GDPR. We process such data only with your explicit consent, which you provide when creating your account and inputting health data into the Services. You may withdraw your consent at any time by contacting us or deleting your account.</p>
<h3>Data Retention for European Residents</h3>
<p>We retain your personal data only for as long as necessary to fulfill the purposes for which it was collected, including satisfying any legal, accounting, or reporting requirements. Upon account deletion, your personal data will be erased within 30 days, unless a longer retention period is required or permitted by law.</p>`,
  },

  termsConditions: {
    title: "Terms & Conditions",
    metaTitle: "Terms & Conditions | xHeal",
    content: `<p><strong>Last Updated: December 15, 2025</strong></p>

<h2>1. Introduction</h2>
<p>Welcome to xHeal. These Terms of Service ("Terms") constitute a legally binding agreement between you ("User," "you," or "your") and xHeal Corp. ("xHeal," "we," "us," or "our"), a company incorporated in the State of Florida, United States, with its principal office located at 25 SE 2ND AVE, SUITE 550, MIAMI, FL 33131, USA.</p>
<p>These Terms govern your access to and use of the xHeal mobile application (the "App"), our website at <a href="https://xheal.ai">https://xheal.ai</a> (the "Website"), and all related services, features, content, and functionality (collectively, the "Services").</p>
<p>By downloading, installing, or using the App, accessing the Website, creating an account, or otherwise using our Services, you acknowledge that you have read, understood, and agree to be bound by these Terms, our <a href="/privacy-policy">Privacy Policy</a>, and our <a href="/cookie-policy">Cookie Policy</a>, which are incorporated herein by reference.</p>
<p>If you do not agree to these Terms, you must not access or use our Services.</p>

<h2>2. Registration and Account Security</h2>
<p>To access certain features of the Services, you must create an account. When you register for an account, you agree to:</p>
<ul>
<li>Provide accurate, current, and complete information during the registration process.</li>
<li>Maintain and promptly update your account information to keep it accurate, current, and complete.</li>
<li>Maintain the security and confidentiality of your login credentials and not share your account with any third party.</li>
<li>Notify us immediately at <a href="mailto:support@xheal.ai">support@xheal.ai</a> if you become aware of any unauthorized use of your account or any other breach of security.</li>
<li>Accept responsibility for all activities that occur under your account.</li>
</ul>
<p>We reserve the right to suspend or terminate your account if any information provided during registration or thereafter proves to be inaccurate, false, outdated, or incomplete, or if we reasonably believe that your account has been compromised.</p>

<h2>3. Eligibility</h2>
<p>You must be at least 13 years of age to use the Services. If you are under 18 years of age (or the age of legal majority in your jurisdiction), you may only use the Services with the consent and supervision of a parent or legal guardian who agrees to be bound by these Terms.</p>
<p>If you are located in the European Union, you must be at least 16 years of age to use the Services. If you are located in the United States, you must be at least 18 years of age to subscribe to paid features.</p>
<p>By using the Services, you represent and warrant that you meet the applicable age requirements and have the legal capacity to enter into these Terms.</p>

<h2>4. Use of Services, Licenses, and Restrictions</h2>
<h3>4.1 Content and AI Technology</h3>
<p>The Services include health and wellness content, AI-generated insights, personalized recommendations, and other informational materials (collectively, "Content"). All Content is provided for general informational and educational purposes only. The AI technology powering our Services uses machine learning algorithms and artificial intelligence models to process health-related data and generate insights. You acknowledge that AI-generated content may contain inaccuracies and should not be relied upon as the sole basis for any health-related decisions.</p>
<h3>4.2 App License</h3>
<p>Subject to your compliance with these Terms, xHeal grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to download, install, and use the App on a personal device that you own or control, solely for your personal, non-commercial use.</p>
<h3>4.3 Prohibited Uses</h3>
<p>You agree not to:</p>
<ul>
<li>Use the Services for any unlawful, fraudulent, or malicious purpose.</li>
<li>Reverse engineer, decompile, disassemble, or attempt to derive the source code of the App or any underlying technology.</li>
<li>Copy, modify, distribute, sell, lease, sublicense, or create derivative works based on the Services or any part thereof.</li>
<li>Use automated systems, bots, scrapers, or similar tools to access, extract data from, or interact with the Services.</li>
<li>Interfere with, disrupt, or attempt to gain unauthorized access to the Services, servers, or networks connected to the Services.</li>
<li>Impersonate any person or entity or misrepresent your affiliation with any person or entity.</li>
<li>Upload, transmit, or distribute any viruses, malware, or other harmful code.</li>
<li>Use the Services to provide medical advice or services to third parties.</li>
<li>Use the Services in any manner that could damage, disable, overburden, or impair xHeal's infrastructure.</li>
</ul>
<h3>4.4 Intellectual Property Ownership</h3>
<p>The Services, including the App, Website, all Content, software, algorithms, AI models, designs, text, graphics, logos, icons, images, audio, video, and all other materials are owned by or licensed to xHeal and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property laws. Nothing in these Terms grants you any right, title, or interest in or to the Services or any Content except for the limited license expressly granted herein.</p>
<h3>4.5 Personal Use Only</h3>
<p>The Services are intended solely for your personal, non-commercial use. You may not use the Services or any Content for commercial purposes without our prior written consent. Any unauthorized use of the Services terminates the licenses granted herein and may subject you to civil and criminal penalties.</p>

<h2>5. Subscriptions, Billing, and Renewals</h2>
<p>xHeal offers subscription-based access to premium features of the Services ("Subscription"). By purchasing a Subscription, you agree to the following:</p>
<ul>
<li><strong>Subscription Plans:</strong> We offer various subscription plans (e.g., monthly, annual) as described in the App or on the Website. Details regarding pricing, features, and billing frequency are provided at the time of purchase.</li>
<li><strong>Automatic Renewal:</strong> Unless you cancel your Subscription before the end of the current billing period, your Subscription will automatically renew for successive periods of the same duration at the then-current price. You authorize us to charge the applicable subscription fee to your designated payment method upon each renewal.</li>
<li><strong>Price Changes:</strong> We reserve the right to change subscription prices at any time. If we change the price of your Subscription, we will provide you with at least 30 days' prior notice. Continued use of the Services after the price change takes effect constitutes your acceptance of the new price.</li>
</ul>

<h2>6. Cancellation and Termination</h2>
<p>You may cancel your Subscription at any time through your account settings in the App or by contacting us at <a href="mailto:support@xheal.ai">support@xheal.ai</a>. Cancellation will take effect at the end of the current billing period. You will continue to have access to premium features until the end of the period for which you have already paid.</p>
<p>We may suspend or terminate your account and access to the Services at any time, with or without cause, and with or without notice. Upon termination, all licenses and rights granted to you under these Terms will immediately cease.</p>
<p><strong>EU Right of Withdrawal:</strong> If you are a consumer located in the European Union, you have the right to withdraw from your Subscription within 14 days of purchase without giving any reason. To exercise this right, you must inform us of your decision by an unequivocal statement (e.g., email to <a href="mailto:support@xheal.ai">support@xheal.ai</a>). If you request to begin the performance of services during the withdrawal period, you will be liable to pay an amount proportionate to the services provided up to the time you communicate your withdrawal.</p>

<h2>7. Free Trials</h2>
<p>xHeal may offer a free trial period of 7 days for new users to experience premium features of the Services. At the end of the free trial, your Subscription will automatically convert to a paid Subscription unless you cancel before the trial period ends.</p>
<p>We reserve the right to modify, suspend, or discontinue free trial offers at any time. Free trial eligibility is limited to one trial per user and may be determined based on your account information, device identifiers, or payment method.</p>

<h2>8. Fees, Payments, and Taxes</h2>
<p>All fees for paid Services are stated in U.S. Dollars (USD) or in the local currency displayed at the time of purchase, and are non-refundable except as expressly provided in these Terms or as required by applicable law.</p>
<p>You are responsible for all applicable taxes, duties, and government charges associated with your use of the Services. If we are required to collect or remit taxes on your behalf, such taxes will be added to the fees charged to you.</p>
<p>Payment processing is handled by third-party payment processors (e.g., Apple App Store, Google Play Store, Stripe). By providing payment information, you represent and warrant that you are authorized to use the payment method and that all payment information is accurate and complete.</p>

<h2>9. No Medical Advice</h2>
<p><strong>THE SERVICES DO NOT PROVIDE MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT.</strong> All Content, including AI-generated insights, health recommendations, scores, and reports, is provided for informational and educational purposes only and is not intended to be a substitute for professional medical advice, diagnosis, or treatment.</p>
<p>Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of information obtained through the Services.</p>
<p>If you think you may have a medical emergency, call your doctor or emergency services immediately. xHeal does not recommend or endorse any specific tests, physicians, products, procedures, opinions, or other information that may be mentioned within the Services.</p>
<p>Reliance on any information provided by the Services, including AI-generated content, is solely at your own risk.</p>

<h2>10. AI Technology</h2>
<p>The Services utilize artificial intelligence and machine learning technologies ("AI Technology") to provide health insights, recommendations, and other features. You acknowledge and agree that:</p>
<ul>
<li>AI Technology has inherent limitations and may produce inaccurate, incomplete, or inappropriate responses.</li>
<li>AI-generated content is based on patterns in data and does not reflect human clinical judgment or expertise.</li>
<li>The accuracy and usefulness of AI Technology outputs depend on the quality and completeness of the data you provide.</li>
<li>We continuously work to improve our AI Technology, but we cannot guarantee that outputs will be free from errors or biases.</li>
<li>You should independently verify any AI-generated health information with qualified healthcare professionals before making health-related decisions.</li>
</ul>

<h2>11. Changes to Services</h2>
<p>We reserve the right to modify, update, suspend, or discontinue any part of the Services at any time, with or without notice. We may also add or remove features, functionalities, or Content. We are not liable to you or any third party for any modification, suspension, or discontinuation of the Services.</p>

<h2>12. User Content</h2>
<p>You may submit, upload, or transmit content through the Services, including health data, messages, feedback, and other materials ("User Content"). You retain ownership of your User Content. However, by submitting User Content, you grant xHeal a worldwide, non-exclusive, royalty-free, sublicensable, and transferable license to use, reproduce, modify, adapt, publish, translate, distribute, and display your User Content solely for the purpose of providing, improving, and developing the Services.</p>
<p>You represent and warrant that:</p>
<ul>
<li>You own or have the necessary rights to your User Content.</li>
<li>Your User Content does not violate the privacy, publicity, intellectual property, or other rights of any third party.</li>
<li>Your User Content does not contain any material that is unlawful, defamatory, obscene, or otherwise objectionable.</li>
</ul>

<h2>13. Disclaimers and Limitation of Liability</h2>
<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY.</p>
<p>XHEAL DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, SECURE, ERROR-FREE, OR FREE FROM VIRUSES OR OTHER HARMFUL COMPONENTS. XHEAL DOES NOT WARRANT THE ACCURACY, COMPLETENESS, OR RELIABILITY OF ANY CONTENT, INCLUDING AI-GENERATED CONTENT.</p>
<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL XHEAL, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AFFILIATES, SUCCESSORS, OR ASSIGNS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE SERVICES.</p>
<p>XHEAL'S TOTAL AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICES SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNTS YOU HAVE PAID TO XHEAL IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS ($100.00).</p>
<p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN WARRANTIES OR LIABILITY. IN SUCH JURISDICTIONS, OUR LIABILITY SHALL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW. FOR USERS IN THE EUROPEAN UNION, NOTHING IN THESE TERMS SHALL EXCLUDE OR LIMIT LIABILITY FOR DEATH OR PERSONAL INJURY CAUSED BY NEGLIGENCE, FRAUD, OR FRAUDULENT MISREPRESENTATION.</p>

<h2>14. Indemnification</h2>
<p>You agree to indemnify, defend, and hold harmless xHeal and its officers, directors, employees, agents, affiliates, successors, and assigns from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of or relating to:</p>
<ul>
<li>Your use of or access to the Services.</li>
<li>Your violation of these Terms.</li>
<li>Your violation of any rights of any third party, including intellectual property, privacy, or publicity rights.</li>
<li>Any User Content you submit, upload, or transmit through the Services.</li>
</ul>
<p><strong>EU Exception:</strong> If you are a consumer resident in the European Union, this indemnification clause applies only to the extent that such indemnification is not prohibited by applicable EU consumer protection laws.</p>

<h2>15. Dispute Resolution and Arbitration</h2>
<p><strong>Mandatory Arbitration:</strong> Any dispute, controversy, or claim arising out of or relating to these Terms or the Services, including the determination of the scope or applicability of this agreement to arbitrate, shall be determined by binding arbitration administered by the American Arbitration Association ("AAA") under its Consumer Arbitration Rules. The arbitration shall be conducted by a single arbitrator and shall take place in Miami-Dade County, Florida, or at a location mutually agreed upon by the parties.</p>
<p><strong>Class Action Waiver:</strong> You and xHeal agree that each party may bring claims against the other only in your or its individual capacity and not as a plaintiff or class member in any purported class, consolidated, or representative proceeding.</p>
<p><strong>30-Day Opt-Out:</strong> You have the right to opt out of this arbitration agreement by sending written notice to <a href="mailto:legal@xheal.ai">legal@xheal.ai</a> within 30 days of first accepting these Terms. Your notice must include your name, address, email address, and an unequivocal statement that you opt out of this arbitration agreement.</p>
<p><strong>Exceptions:</strong> Nothing in this section shall prevent either party from seeking injunctive or other equitable relief from a court of competent jurisdiction. For users located in the European Union, this arbitration clause shall not deprive you of the protection afforded by mandatory provisions of the law of the EU Member State in which you are habitually resident, including the right to bring proceedings before the courts of that Member State.</p>

<h2>16. Governing Law</h2>
<p>These Terms shall be governed by and construed in accordance with the laws of the State of Florida, United States, without regard to its conflict of law provisions. For users in the European Union, this choice of law does not deprive you of the protection afforded by mandatory consumer protection provisions in your country of residence.</p>

<h2>17. Changes to These Terms</h2>
<p>We reserve the right to modify these Terms at any time. If we make material changes, we will notify you by posting the updated Terms within the App, on the Website, or by sending you a notification. Your continued use of the Services after the changes take effect constitutes your acceptance of the revised Terms. If you do not agree to the revised Terms, you must stop using the Services and cancel your Subscription.</p>

<h2>18. General Provisions</h2>
<ul>
<li><strong>Entire Agreement:</strong> These Terms, together with the Privacy Policy and Cookie Policy, constitute the entire agreement between you and xHeal regarding the Services and supersede all prior or contemporaneous agreements, understandings, and communications.</li>
<li><strong>Severability:</strong> If any provision of these Terms is found to be invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect.</li>
<li><strong>Waiver:</strong> Our failure to enforce any right or provision of these Terms shall not be deemed a waiver of such right or provision.</li>
<li><strong>Assignment:</strong> You may not assign or transfer these Terms or any rights or obligations hereunder without our prior written consent. We may assign our rights and obligations under these Terms without restriction.</li>
<li><strong>Force Majeure:</strong> xHeal shall not be liable for any failure or delay in performance resulting from causes beyond its reasonable control, including but not limited to acts of God, war, terrorism, pandemics, natural disasters, government actions, or failures of third-party services.</li>
</ul>

<h2>19. Upgrade Policy</h2>
<p>If you upgrade your Subscription plan during an active billing period, the new plan will take effect immediately. You will be charged the prorated difference between your current plan and the upgraded plan for the remainder of the billing period. Subsequent billing cycles will reflect the full price of the upgraded plan.</p>

<h2>20. Contact Us</h2>
<p>If you have any questions about these Terms, please contact us at:</p>
<p><strong>xHeal Corp.</strong><br>25 SE 2ND AVE, SUITE 550<br>MIAMI, FL 33131, USA<br>Email: <a href="mailto:legal@xheal.ai">legal@xheal.ai</a><br>Support: <a href="mailto:support@xheal.ai">support@xheal.ai</a><br>Phone: (833) 514-4187</p>`,
  },

  cookiePolicy: {
    title: "Cookie Policy",
    metaTitle: "Cookie Policy | xHeal",
    content: `<p><strong>Effective Date: November 22, 2025</strong></p>

<h2>1. What Are Cookies?</h2>
<p>Cookies are small text files that are placed on your device (computer, tablet, or mobile phone) when you visit a website. Cookies are widely used to make websites work more efficiently, to provide a better user experience, and to supply information to the website owners.</p>
<p>Cookies can be "first-party cookies" (set by the website you are visiting) or "third-party cookies" (set by a domain other than the website you are visiting). Cookies can also be classified by their duration: "session cookies" are deleted when you close your browser, while "persistent cookies" remain on your device for a set period or until you delete them.</p>

<h2>2. How xHeal Uses Cookies</h2>
<p>xHeal Corp. ("xHeal," "we," "us," or "our") uses cookies and similar tracking technologies on our website at <a href="https://xheal.ai">https://xheal.ai</a> (the "Website") for the following purposes:</p>
<ul>
<li><strong>Essential Cookies:</strong> These cookies are strictly necessary for the operation of our Website. They enable core functionality such as security, network management, and accessibility. You cannot opt out of these cookies as the Website cannot function properly without them.</li>
<li><strong>Performance and Analytics Cookies:</strong> These cookies collect information about how visitors use our Website, such as which pages are visited most often, how visitors navigate the site, and whether they encounter error messages. The information collected by these cookies is aggregated and anonymous. We use this data to improve the performance and usability of our Website.</li>
<li><strong>Functional Cookies:</strong> These cookies allow our Website to remember choices you make (such as your preferred language or region) and provide enhanced, personalized features. They may also be used to provide services you have requested, such as watching a video or commenting on a blog post.</li>
<li><strong>Targeting and Advertising Cookies:</strong> These cookies are used to deliver advertisements that are more relevant to you and your interests. They are also used to limit the number of times you see an advertisement and to measure the effectiveness of advertising campaigns. They are typically placed by advertising networks with the website operator's permission.</li>
</ul>

<h2>3. Types of Cookies We Use</h2>
<h3>3.1 First-Party Cookies</h3>
<p>These are cookies set directly by xHeal when you visit our Website. They include:</p>
<ul>
<li><strong>Session Management:</strong> Cookies that maintain your session state as you navigate the Website, ensuring a seamless browsing experience.</li>
<li><strong>Preference Cookies:</strong> Cookies that store your preferences and settings, such as language, region, and display options.</li>
<li><strong>Authentication Cookies:</strong> Cookies that identify you when you log in to your account, so you do not need to re-enter your credentials on each page.</li>
</ul>
<h3>3.2 Third-Party Cookies</h3>
<p>These are cookies set by third-party services integrated into our Website. They may include:</p>
<ul>
<li><strong>Analytics Providers:</strong> We use third-party analytics services (e.g., Google Analytics, Mixpanel) to understand how visitors interact with our Website. These services use cookies to collect data about your use of the Website, which is then used to compile reports and help us improve the Website.</li>
<li><strong>Advertising Partners:</strong> We may use third-party advertising partners who set cookies to help deliver targeted advertisements based on your browsing behavior and interests.</li>
<li><strong>Social Media Plugins:</strong> Our Website may include social media features (e.g., share buttons) provided by third parties. These features may set cookies to enable proper functionality and track your interaction with the feature.</li>
</ul>

<h2>4. Similar Technologies</h2>
<p>In addition to cookies, we may use similar technologies including:</p>
<ul>
<li><strong>Pixels (Web Beacons):</strong> Small transparent images embedded in web pages or emails that allow us to track whether a page or email has been viewed and to gather certain technical information.</li>
<li><strong>Local Storage:</strong> Technologies that allow websites to store data locally on your device. Local storage is similar to cookies but can store larger amounts of data.</li>
<li><strong>Fingerprinting:</strong> A technique that collects information about your device configuration (e.g., browser type, screen resolution, installed plugins) to create a unique identifier. We do not use device fingerprinting for tracking purposes.</li>
</ul>

<h2>5. How to Manage Your Cookie Preferences</h2>
<p>You have several options for managing cookies:</p>
<ul>
<li><strong>Cookie Consent Banner:</strong> When you first visit our Website, you will be presented with a cookie consent banner that allows you to accept or customize your cookie preferences. You can update your preferences at any time by clicking the cookie settings link in the footer of our Website.</li>
<li><strong>Browser Settings:</strong> Most web browsers allow you to control cookies through their settings. You can set your browser to refuse all cookies, accept only first-party cookies, or delete cookies when you close your browser. Please note that if you disable cookies, some features of our Website may not function properly.</li>
</ul>
<p>For instructions on how to manage cookies in your browser, please visit the support pages for your browser:</p>
<ul>
<li><a href="https://support.google.com/chrome/answer/95647" target="_blank" rel="noopener noreferrer">Google Chrome</a></li>
<li><a href="https://support.apple.com/guide/safari/manage-cookies-sfri11471" target="_blank" rel="noopener noreferrer">Apple Safari</a></li>
<li><a href="https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox" target="_blank" rel="noopener noreferrer">Mozilla Firefox</a></li>
<li><a href="https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies" target="_blank" rel="noopener noreferrer">Microsoft Internet Explorer</a></li>
</ul>
<ul>
<li><strong>Opt-Out Tools:</strong> You can opt out of interest-based advertising from participating companies by visiting the <a href="https://optout.aboutads.info/" target="_blank" rel="noopener noreferrer">Digital Advertising Alliance (DAA)</a> or the <a href="https://www.youronlinechoices.eu/" target="_blank" rel="noopener noreferrer">European Interactive Digital Advertising Alliance (EDAA)</a>.</li>
<li><strong>Do Not Track:</strong> Some browsers support a "Do Not Track" (DNT) setting that signals to websites that you do not want to be tracked. At this time, our Website does not respond to DNT signals, but we respect your cookie preferences as set through our cookie consent banner.</li>
</ul>

<h2>6. Data Collected Through Cookies</h2>
<p>The data collected through cookies may include:</p>
<ul>
<li>IP address and general geographic location.</li>
<li>Browser type and version.</li>
<li>Operating system.</li>
<li>Referring URL (the page that directed you to our Website).</li>
<li>Pages visited and links clicked on our Website.</li>
<li>Time and date of visits.</li>
<li>Duration of sessions.</li>
<li>Device type and screen resolution.</li>
</ul>
<p>This data is processed in accordance with our <a href="/privacy-policy">Privacy Policy</a>.</p>

<h2>7. Cookies and the GDPR / ePrivacy Directive</h2>
<p>If you are located in the European Economic Area (EEA), United Kingdom (UK), or Switzerland, we comply with the requirements of the General Data Protection Regulation (GDPR) and the ePrivacy Directive (Cookie Law) regarding the use of cookies:</p>
<ul>
<li>We obtain your consent before placing non-essential cookies on your device.</li>
<li>We provide clear and comprehensive information about the cookies we use and their purposes.</li>
<li>We allow you to withdraw your consent at any time by updating your cookie preferences.</li>
<li>Essential cookies that are strictly necessary for the operation of the Website do not require consent.</li>
</ul>

<h2>8. Changes to This Cookie Policy</h2>
<p>We may update this Cookie Policy from time to time to reflect changes in our practices, technologies, legal requirements, or other factors. If we make material changes, we will notify you by posting the updated policy on our Website and updating the "Effective Date" at the top of this page. We encourage you to review this Cookie Policy periodically for any changes.</p>

<h2>9. Contact Us</h2>
<p>If you have any questions about this Cookie Policy or our use of cookies, please contact us at:</p>
<p><strong>xHeal Corp.</strong><br>25 SE 2ND AVE, SUITE 550<br>MIAMI, FL 33131, USA<br>Email: <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a><br>Support: <a href="mailto:support@xheal.ai">support@xheal.ai</a><br>Phone: (833) 514-4187</p>`,
  },
};

// ============================================================
// BULGARIAN
// ============================================================

const legalBg: LegalPages = {
  privacyPolicy: {
    title: "\u041F\u043E\u043B\u0438\u0442\u0438\u043A\u0430 \u0437\u0430 \u043F\u043E\u0432\u0435\u0440\u0438\u0442\u0435\u043B\u043D\u043E\u0441\u0442",
    metaTitle: "\u041F\u043E\u043B\u0438\u0442\u0438\u043A\u0430 \u0437\u0430 \u043F\u043E\u0432\u0435\u0440\u0438\u0442\u0435\u043B\u043D\u043E\u0441\u0442 | xHeal",
    content: `<p><strong>Последна актуализация: 15 декември 2025 г.</strong></p>

<h2>1. Въведение</h2>
<p>xHeal Corp. (\u201ExHeal\u201C, \u201Eние\u201C, \u201Eнас\u201C или \u201Eнашият/нашата/нашите\u201C) се ангажира да защитава поверителността и сигурността на вашите лични данни. Тази Политика за поверителност (\u201EПолитика\u201C) обяснява как събираме, използваме, споделяме и защитаваме информация, когато използвате мобилното приложение xHeal (\u201EПриложението\u201C), нашия уебсайт на <a href="https://xheal.ai">https://xheal.ai</a> (\u201EУебсайтът\u201C) и всички свързани услуги, функции, съдържание и функционалност (общо \u201EУслугите\u201C).</p>
<p>xHeal Corp. е регистрирана в щата Флорида, Съединени щати, с главен офис на 25 SE 2ND AVE, SUITE 550, MIAMI, FL 33131, USA. За целите на приложимите закони за защита на данните xHeal Corp. е администраторът на данни, отговорен за вашите лични данни.</p>
<p>Използвайки нашите Услуги, вие потвърждавате, че сте прочели и разбрали тази Политика. Ако не сте съгласни с тази Политика, моля, не използвайте нашите Услуги.</p>

<h2>2. Как събираме лични данни</h2>
<p>Събираме лични данни по следните начини:</p>
<ul>
<li><strong>Директно от вас:</strong> Когато създавате акаунт, попълвате здравния си профил, въвеждате здравни данни, използвате xHeal Chat, качвате медицински документи, се абонирате за нашите Услуги или се свързвате с екипа ни за поддръжка.</li>
<li><strong>Автоматично:</strong> Когато използвате нашите Услуги, ние автоматично събираме определени технически данни и данни за използване чрез бисквитки, лог файлове, аналитични инструменти и подобни технологии.</li>
<li><strong>От източници на трети страни:</strong> Може да получаваме данни от свързани здравни устройства и носими устройства (напр. Apple Health, Google Health Connect), доставчици на вход от трети страни (напр. Apple Sign-In, Google Sign-In), обработващи плащания и доставчици на аналитика.</li>
</ul>

<h2>3. Какви лични данни събираме</h2>
<p>Може да събираме следните категории лични данни:</p>
<ul>
<li><strong>Информация за акаунта:</strong> Име, имейл адрес, парола (криптирана), дата на раждане, пол, профилна снимка и предпочитания за акаунта.</li>
<li><strong>Здравни данни и данни за уелнес:</strong> Жизнени показатели (напр. сърдечна честота, кръвно налягане, тегло, телесна температура), медицински документи, които качвате, дневници за симптоми и обостряния, хранителна информация, данни за упражнения и активност, данни за сън, входни данни за психическо здраве и здравни оценки, генерирани от нашите Услуги.</li>
<li><strong>Данни от устройства и носими устройства:</strong> Данни, синхронизирани от свързани здравни устройства, Apple Health, Google Health Connect и други здравни платформи на трети страни, които упълномощавате.</li>
<li><strong>Данни за използване:</strong> Информация за това как взаимодействате с нашите Услуги, включително използвани функции, посетени страници, прекарано време, кликвания и навигационни модели.</li>
<li><strong>Информация за устройството:</strong> Тип устройство, операционна система и версия, уникални идентификатори на устройството, IP адрес, тип браузър и езикови предпочитания.</li>
<li><strong>Информация за плащане:</strong> Данните за метода на плащане се обработват от обработващи плащания трети страни (напр. Apple, Google, Stripe). Ние не съхраняваме пълния номер на кредитната ви карта или платежни идентификационни данни на нашите сървъри.</li>
<li><strong>Данни от комуникации:</strong> Съобщения, изпратени чрез xHeal Chat, запитвания за поддръжка, обратна връзка и всякакви други комуникации, които имате с нас.</li>
<li><strong>Данни за местоположение:</strong> Обща информация за местоположението, извлечена от вашия IP адрес. Не събираме точни GPS данни за местоположение.</li>
</ul>

<h2>4. Бисквитки и подобни технологии</h2>
<p>Използваме бисквитки, пиксели и подобни технологии за проследяване на нашия Уебсайт и в нашите Услуги, за да подобрим вашето изживяване, анализираме използването и доставяме подходящо съдържание. За подробна информация относно бисквитките, които използваме, и как да управлявате предпочитанията си, моля, вижте нашата <a href="/cookie-policy">Политика за бисквитки</a>.</p>

<h2>5. Как използваме събраните лични данни</h2>
<p>Използваме вашите лични данни за следните цели:</p>
<ul>
<li><strong>Предоставяне и подобряване на Услугите:</strong> За управление, поддържане и подобряване на Услугите, включително генериране на здравни прозрения, оценки, доклади и персонализирани препоръки.</li>
<li><strong>Функции, задвижвани от AI:</strong> За обучение, разработване и подобряване на нашите AI модели и модели за машинно обучение, които задвижват здравните прозрения и xHeal Chat. Когато използваме вашите данни за AI обучение, те са анонимизирани и агрегирани, така че не могат да ви идентифицират лично.</li>
<li><strong>Управление на акаунта:</strong> За създаване и управление на вашия акаунт, обработка на абонаменти и плащания и предоставяне на клиентска поддръжка.</li>
<li><strong>Комуникации:</strong> За изпращане на транзакционни съобщения (напр. потвърждения за акаунт, известия за фактуриране, предупреждения за сигурност), както и маркетингови и промоционални комуникации, когато сте се съгласили.</li>
<li><strong>Аналитика и проучвания:</strong> За разбиране на тенденциите в използването, наблюдение на ефективността на нашите Услуги, провеждане на изследвания и анализи и разработване на нови функции.</li>
<li><strong>Сигурност и предотвратяване на измами:</strong> За откриване, предотвратяване и справяне със сигурностни инциденти, измами и други вредни дейности.</li>
<li><strong>Правно съответствие:</strong> За спазване на приложимите закони, разпоредби, правни процеси и правителствени заявки.</li>
</ul>

<h2>6. Как споделяме лични данни</h2>
<p>Ние не продаваме вашите лични данни. Може да споделяме вашите лични данни при следните обстоятелства:</p>
<ul>
<li><strong>Доставчици на услуги:</strong> Споделяме данни с доверени доставчици на услуги трети страни, които изпълняват функции от наше име, като облачен хостинг (AWS), аналитика, обработка на плащания, доставка на имейли и клиентска поддръжка. Тези доставчици са договорно задължени да защитават вашите данни и могат да ги използват само за целите, определени от нас.</li>
<li><strong>Доставчици на AI технологии:</strong> Може да споделяме анонимизирани и деидентифицирани данни с доставчици на AI технологии трети страни за захранване на определени функции на Услугите, като xHeal Chat. Не споделяме лично идентифицируема здравна информация с тези доставчици без вашето изрично съгласие.</li>
<li><strong>Правни изисквания:</strong> Може да разкриваме вашите данни, когато се изисква от закон, регулация, правен процес или правителствена заявка, или когато смятаме, че разкриването е необходимо за защита на правата, собствеността или безопасността на xHeal, нашите потребители или други.</li>
<li><strong>Бизнес трансфери:</strong> В случай на сливане, придобиване, реорганизация или продажба на всички или част от нашите активи, вашите лични данни могат да бъдат прехвърлени на придобиващото лице.</li>
<li><strong>С вашето съгласие:</strong> Може да споделяме вашите данни за други цели с вашето изрично съгласие.</li>
</ul>

<h2>7. Как можете да споделяте лични данни</h2>
<p>Услугите могат да ви позволят да споделяте вашите здравни данни, доклади или друга информация с трети страни, като лекари, членове на семейството или други лица, които посочите. Когато изберете да споделите данните си с трети страни, тяхното използване на вашите данни се регулира от техните собствени практики и политики за поверителност. xHeal не е отговорен за практиките за поверителност на трети страни, с които споделяте данните си.</p>

<h2>8. xHeal Chat и AI технологии на трети страни</h2>
<p>Функцията xHeal Chat се захранва от технология за изкуствен интелект, която може да включва AI модели на трети страни. Когато взаимодействате с xHeal Chat:</p>
<ul>
<li>Вашите съобщения и входни данни се обработват за генериране на отговори и здравни прозрения.</li>
<li>Може да предаваме анонимизирани или деидентифицирани части от вашите входни данни на доставчици на AI трети страни за улесняване на отговорите.</li>
<li>Прилагаме технически и организационни мерки за минимизиране на личните данни, споделени с доставчици на AI трети страни.</li>
<li>Чат разговорите могат да бъдат съхранени за подобряване на качеството и точността на бъдещите взаимодействия и за подобряване на нашите AI модели.</li>
<li>Не трябва да споделяте високочувствителна лична информация (напр. номера на социално осигуряване, номера на финансови сметки) в чат разговори.</li>
</ul>

<h2>9. Вашите възможности за избор</h2>
<p>Имате следните възможности относно вашите лични данни:</p>
<ul>
<li><strong>Информация за акаунта:</strong> Можете да преглеждате и актуализирате информацията за акаунта си чрез настройките на Приложението по всяко време.</li>
<li><strong>Маркетингови комуникации:</strong> Можете да се откажете от маркетингови имейли, като кликнете на линка \u201Eотписване\u201C във всеки маркетингов имейл или като актуализирате комуникационните си предпочитания в настройките на Приложението.</li>
<li><strong>Бисквитки:</strong> Можете да управлявате предпочитанията си за бисквитки чрез настройките на браузъра или чрез механизма за съгласие за бисквитки на нашия Уебсайт. Вижте нашата <a href="/cookie-policy">Политика за бисквитки</a> за повече подробности.</li>
<li><strong>Преносимост на данните:</strong> Можете да поискате копие на вашите лични данни в структуриран, общоизползван и машинночитаем формат, като се свържете с нас на <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a>.</li>
<li><strong>Изтриване на акаунта:</strong> Можете да поискате изтриване на вашия акаунт и свързаните лични данни, като се свържете с нас на <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a> или чрез настройките на акаунта в Приложението. Моля, имайте предвид, че някои данни могат да бъдат задържани, както се изисква от закона или за легитимни бизнес цели.</li>
<li><strong>Свързани устройства:</strong> Можете да прекъснете връзката на здравни устройства и носими устройства от Приложението по всяко време чрез настройките на Приложението.</li>
</ul>

<h2>10. Сигурност и съхранение на данните</h2>
<p>Прилагаме индустриални стандартни технически и организационни мерки за сигурност, за да защитим вашите лични данни срещу неоторизиран достъп, промяна, разкриване или унищожаване. Тези мерки включват криптиране при пренос (TLS) и в покой (AES-256), контрол на достъпа, редовни оценки на сигурността и сигурна облачна инфраструктура (AWS).</p>
<p>Въпреки това, никой метод за предаване по Интернет или метод за електронно съхранение не е 100% сигурен. Въпреки че се стремим да използваме търговски приемливи средства за защита на вашите лични данни, не можем да гарантираме абсолютната им сигурност.</p>
<p>Съхраняваме вашите лични данни, докато акаунтът ви е активен или доколкото е необходимо за предоставяне на Услугите. Когато акаунтът ви бъде изтрит, ще изтрием или анонимизираме вашите лични данни в рамките на 90 дни, с изключение на случаите, когато задържането се изисква от закон, за разрешаване на спорове или за легитимни бизнес цели. Анонимизирани и агрегирани данни, които не могат да ви идентифицират, могат да бъдат съхранени за неопределено време за целите на проучвания и аналитика.</p>

<h2>11. Услугите не са предназначени за деца</h2>
<p>Нашите Услуги не са насочени към деца под 13 години (или 16 в Европейския съюз). Ние съзнателно не събираме лични данни от деца под тези възрасти. Ако разберем, че сме събрали лични данни от дете под приложимия възрастов праг, ще предприемем стъпки за незабавно изтриване на такива данни. Ако смятате, че дете ни е предоставило лични данни, моля, свържете се с нас на <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a>.</p>

<h2>12. Промени в тази Политика за поверителност</h2>
<p>Може да актуализираме тази Политика от време на време. Ако направим съществени промени, ще ви уведомим, като публикуваме актуализираната Политика на Уебсайта и в Приложението, и когато се изисква от закон, като ви изпратим имейл или известие в приложението. Датата \u201EПоследна актуализация\u201C в горната част на тази Политика показва кога е била последно ревизирана. Продължаването на използването на Услугите след датата на влизане в сила на ревизираната Политика означава приемане на промените.</p>

<h2>13. Свържете се с нас</h2>
<p>Ако имате въпроси, притеснения или заявки относно тази Политика за поверителност или нашите практики за данни, моля, свържете се с нас:</p>
<p><strong>xHeal Corp.</strong><br>25 SE 2ND AVE, SUITE 550<br>MIAMI, FL 33131, USA</p>
<ul>
<li>Общи запитвания за поверителност: <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a></li>
<li>Длъжностно лице по защита на данните: <a href="mailto:dpo@xheal.ai">dpo@xheal.ai</a></li>
<li>Представител за ЕС: <a href="mailto:eu-representative@xheal.ai">eu-representative@xheal.ai</a></li>
<li>Поддръжка: <a href="mailto:support@xheal.ai">support@xheal.ai</a></li>
<li>Правен отдел: <a href="mailto:legal@xheal.ai">legal@xheal.ai</a></li>
<li>Телефон: (833) 514-4187</li>
</ul>

<h2>14. Уведомление за поверителност за конкретни щати на САЩ</h2>
<p>Този раздел предоставя допълнителна информация за жители на щати в САЩ с цялостно законодателство за поверителност, включително Калифорния (CCPA/CPRA), Вирджиния (VCDPA), Колорадо (CPA), Кънектикът (CTDPA) и други щати с подобни закони.</p>
<h3>Категории събрана лична информация</h3>
<p>През предходните 12 месеца сме събрали следните категории лична информация, както е дефинирана в приложимите щатски закони за поверителност:</p>
<ul>
<li>Идентификатори (напр. име, имейл адрес, ID на акаунт, IP адрес).</li>
<li>Категории лична информация, изброени в съответните щатски закони (напр. име, адрес, телефонен номер).</li>
<li>Защитени класификационни характеристики (напр. възраст, пол).</li>
<li>Търговска информация (напр. история на абонаменти, платежни записи).</li>
<li>Интернет или друга електронна мрежова активност (напр. история на сърфиране, данни за взаимодействие, информация за устройството).</li>
<li>Сензорни данни (напр. здравни данни, биометрични данни от свързани устройства).</li>
<li>Изведени заключения от горното (напр. здравни оценки и AI прозрения).</li>
</ul>
<h3>Вашите права за поверителност по щат</h3>
<p>В зависимост от щата на местоживеене може да имате следните права:</p>
<ul>
<li><strong>Право да знаете:</strong> Да поискате информация за категориите и конкретните части от лична информация, която сме събрали за вас.</li>
<li><strong>Право на изтриване:</strong> Да поискате изтриване на лична информация, която сме събрали от вас, при определени изключения.</li>
<li><strong>Право на корекция:</strong> Да поискате корекция на неточна лична информация.</li>
<li><strong>Право на отказ:</strong> Да се откажете от продажбата или споделянето на лична информация. xHeal не продава вашата лична информация.</li>
<li><strong>Право на недискриминация:</strong> Да упражнявате правата си за поверителност без дискриминационно третиране.</li>
</ul>
<p>За упражняване на някое от тези права се свържете с нас на <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a>. Ще потвърдим самоличността ви, преди да обработим заявката ви.</p>

<h2>15. Трансатлантическа рамка за поверителност на данните</h2>
<p>xHeal може да прехвърля лични данни от Европейското икономическо пространство (ЕИП), Обединеното кралство (ОК) и Швейцария към Съединените щати. Когато правим това, разчитаме на следните механизми за трансфер, за да осигурим адекватна защита на вашите данни:</p>
<ul>
<li><strong>Стандартни договорни клаузи (СДК):</strong> Сключваме одобрени от ЕС Стандартни договорни клаузи с нашите доставчици на услуги и партньори, които обработват данни извън ЕИП.</li>
<li><strong>Решения за адекватност:</strong> Когато е приложимо, прехвърляме данни към държави, за които Европейската комисия е определила, че осигуряват адекватно ниво на защита на данните.</li>
<li><strong>Допълнителни мерки:</strong> Прилагаме допълнителни технически и организационни мерки (напр. криптиране, контрол на достъпа), за да допълним защитите, предоставени от СДК, когато е необходимо.</li>
</ul>
<p>За допълнителна информация относно нашите практики за трансграничен трансфер на данни, моля, свържете се с нашето Длъжностно лице по защита на данните на <a href="mailto:dpo@xheal.ai">dpo@xheal.ai</a>.</p>

<h2>16. Уведомление за поверителност за европейски резиденти (GDPR)</h2>
<p>Този раздел предоставя допълнителна информация за лица, намиращи се в Европейското икономическо пространство (ЕИП), Обединеното кралство (ОК) и Швейцария, както се изисква от Общия регламент за защита на данните (GDPR) и еквивалентното законодателство.</p>
<h3>Правни основания за обработка</h3>
<p>Обработваме вашите лични данни на следните правни основания:</p>
<ul>
<li><strong>Изпълнение на договор:</strong> Обработка, необходима за изпълнение на нашия договор с вас (напр. предоставяне на Услугите, управление на акаунта ви, обработка на плащания).</li>
<li><strong>Съгласие:</strong> Обработка, базирана на вашето свободно дадено, конкретно, информирано и недвусмислено съгласие (напр. обработка на специални категории здравни данни, изпращане на маркетингови комуникации).</li>
<li><strong>Легитимни интереси:</strong> Обработка, необходима за нашите легитимни интереси, при условие че тези интереси не са надвишени от вашите основни права и свободи (напр. подобряване на нашите Услуги, предотвратяване на измами, сигурност).</li>
<li><strong>Правно задължение:</strong> Обработка, необходима за спазване на правни задължения, на които сме подчинени.</li>
</ul>
<h3>Вашите права по GDPR</h3>
<p>Като субект на данни в ЕИП, ОК или Швейцария имате следните права:</p>
<ul>
<li><strong>Право на достъп:</strong> Да поискате копие на личните данни, които съхраняваме за вас.</li>
<li><strong>Право на коригиране:</strong> Да поискате корекция на неточни или непълни лични данни.</li>
<li><strong>Право на изтриване:</strong> Да поискате изтриване на вашите лични данни при определени обстоятелства.</li>
<li><strong>Право на ограничаване:</strong> Да поискате ограничаване на обработката на вашите лични данни при определени обстоятелства.</li>
<li><strong>Право на преносимост на данните:</strong> Да получите вашите лични данни в структуриран, общоизползван и машинночитаем формат.</li>
<li><strong>Право на възражение:</strong> Да възразите срещу обработката на вашите лични данни, базирана на легитимни интереси или за целите на директен маркетинг.</li>
<li><strong>Право на оттегляне на съгласие:</strong> Когато обработката е базирана на съгласие, имате правото да оттеглите съгласието си по всяко време, без това да засяга законосъобразността на обработката, базирана на съгласие преди оттеглянето му.</li>
<li><strong>Право на подаване на жалба:</strong> Имате правото да подадете жалба до местния орган за защита на данните (надзорен орган).</li>
</ul>
<p>За упражняване на някое от тези права, моля, свържете се с нашето Длъжностно лице по защита на данните на <a href="mailto:dpo@xheal.ai">dpo@xheal.ai</a> или нашия Представител за ЕС на <a href="mailto:eu-representative@xheal.ai">eu-representative@xheal.ai</a>.</p>
<h3>Специални категории данни</h3>
<p>Определени здравни данни и данни за уелнес, които обработваме, могат да представляват \u201Eспециални категории лични данни\u201C по GDPR. Обработваме такива данни само с вашето изрично съгласие, което предоставяте при създаването на акаунт и въвеждането на здравни данни в Услугите. Можете да оттеглите съгласието си по всяко време, като се свържете с нас или изтриете акаунта си.</p>
<h3>Съхранение на данни за европейски резиденти</h3>
<p>Съхраняваме вашите лични данни само толкова дълго, колкото е необходимо за изпълнение на целите, за които са събрани, включително за удовлетворяване на правни, счетоводни или отчетни изисквания. При изтриване на акаунта вашите лични данни ще бъдат изтрити в рамките на 30 дни, освен ако по-дълъг период на съхранение не се изисква или разрешава от закон.</p>`,
  },

  termsConditions: {
    title: "\u041E\u0431\u0449\u0438 \u0443\u0441\u043B\u043E\u0432\u0438\u044F",
    metaTitle: "\u041E\u0431\u0449\u0438 \u0443\u0441\u043B\u043E\u0432\u0438\u044F | xHeal",
    content: `<p><strong>Последна актуализация: 15 декември 2025 г.</strong></p>
<p>Поради обема на документа, пълният текст на Общите условия на български език е наличен при поискване. Моля, свържете се с нас на <a href="mailto:legal@xheal.ai">legal@xheal.ai</a> за пълната версия на български. Правно обвързващата версия е на английски език.</p>
<p>The legally binding version of the Terms &amp; Conditions is in English. Please switch to English to read the full Terms &amp; Conditions.</p>`,
  },

  cookiePolicy: {
    title: "\u041F\u043E\u043B\u0438\u0442\u0438\u043A\u0430 \u0437\u0430 \u0431\u0438\u0441\u043A\u0432\u0438\u0442\u043A\u0438",
    metaTitle: "\u041F\u043E\u043B\u0438\u0442\u0438\u043A\u0430 \u0437\u0430 \u0431\u0438\u0441\u043A\u0432\u0438\u0442\u043A\u0438 | xHeal",
    content: `<p><strong>Последна актуализация: 15 декември 2025 г.</strong></p>
<p>Поради обема на документа, пълният текст на Политиката за бисквитки на български език е наличен при поискване. Моля, свържете се с нас на <a href="mailto:privacy@xheal.ai">privacy@xheal.ai</a> за пълната версия на български. Правно обвързващата версия е на английски език.</p>
<p>The legally binding version of the Cookie Policy is in English. Please switch to English to read the full Cookie Policy.</p>`,
  },
};

export function getLegalContent(locale: string = "en"): LegalPages {
  return locale === "bg" ? legalBg : legalEn;
}
